export const FETCH_RELEASE_TOGGLES = 'FETCH_RELEASE_TOGGLES';
export const UPDATE_RELEASE_TOGGLES = 'UPDATE_RELEASE_TOGGLES';
export const FETCH_RELEASE_TOGGLES_FAILED = 'FETCH_RELEASE_TOGGLES_FAILED';

export const SHOW_EDIT_TOGGLE_MODAL = 'SHOW_EDIT_TOGGLE_MODAL';
export const HIDE_EDIT_TOGGLE_MODAL = 'HIDE_EDIT_TOGGLE_MODAL';

export const EDIT_TOGGLE_CATEGORY_CHANGE = 'EDIT_TOGGLE_CATEGORY_CHANGE';
export const EDIT_TOGGLE_NAME_CHANGE = 'EDIT_TOGGLE_NAME_CHANGE';
export const EDIT_TOGGLE_DESCRIPTION_CHANGE = 'EDIT_TOGGLE_DESCRIPTION_CHANGE';
export const EDIT_TOGGLE_ACTIVE_CHANGED = 'EDIT_TOGGLE_ACTIVE_CHANGED';

export const REQUEST_TOGGLE_EDIT = 'REQUEST_TOGGLE_EDIT';
export const REQUEST_TOGGLE_EDIT_SUCCESS = 'REQUEST_TOGGLE_EDIT_SUCCESS';
export const REQUEST_TOGGLE_EDIT_FAILED = 'REQUEST_TOGGLE_EDIT_FAILED';
