export const FETCH_RELEASE_TOGGLES = 'FETCH_RELEASE_TOGGLES';
export const UPDATE_RELEASE_TOGGLES = 'UPDATE_RELEASE_TOGGLES';
export const FETCH_RELEASE_TOGGLES_FAILED = 'FETCH_RELEASE_TOGGLES_FAILED';

export const SHOW_EDIT_TOGGLE_MODAL = 'SHOW_EDIT_TOGGLE_MODAL';
export const HIDE_EDIT_TOGGLE_MODAL = 'HIDE_EDIT_TOGGLE_MODAL';